# Personal info
name: Julio Eduardo Orozco
location: Muncie, IN, 47304
phone: +1 (765) 228-3614
email: jeorozco2002@gmail.com
github: https://github.com/jeorozc0

# Experience Section
experience:
  - title: Front Desk Assistant
    organization: Scheidler Apartments, Ball State University
    location: Muncie, IN
    duration: September 2022 - February 2023
    responsibilities:
      - Provided excellent customer service to apartment residents, resolving issues and organizing documents.
      - Cultivated positive community relations through effective communication and conflict resolution.
  - title: Website Designer
    organization: Global Institute of Entrepreneurship
    location: Managua, Nicaragua
    duration: April 2018 - January 2019
    responsibilities:
      - Designed and created portfolio websites for students at the institute.
      - Independently designed and created websites using Adobe Suite, HTML, CSS, and JavaScript.

# Projects Section
projects:
  - title: Personalized Learning Website
    link: https://github.com/hergin/PersonalizedLearningPlanWebApp
    description: |
      Led a team to develop a full-stack goal tracker web application for Stanford CME, enabling users to easily track learning modules and milestones.
      Utilized React.js, Node.js, and PostgreSQL to create a high-performance, scalable application with efficient and reusable components.
      Implemented state management, UX/UI design, and authentication to enhance user experience and ensure secure access.
      Designed and optimized a scalable back-end architecture, improving database performance and ensuring high availability.
  - title: StrengthSync
    link: http://strenght-sync.vercel.app
    description: |
      Developed StrengthSync, a next-generation exercise companion, using React, TypeScript, Tailwind, and Supabase.
      Focused on intuitive UI/UX design and dynamic tracking features for an enhanced user experience.
      Created tools for intuitive workout creation and quality tracking capabilities, providing users with a seamless fitness tracking experience.

# Education Section
education:
  - degree: Bachelor of Science (B.S.) - Computer Science
    institution: Ball State University
    location: Muncie, IN
    duration: August 2020 - May 2024

# Skills Section
skills:
  programming_languages: 
    - JavaScript (ES6+)
    - TypeScript
    - Python
    - Java
    - SQL/Postgres
    - HTML/CSS
  frameworks: 
    - React.js (v16+)
    - Next.js
    - React Native
    - Node.js/Express
    - Tailwind CSS
  tools: 
    - Git
    - Docker
    - CI/CD
    - AWS
    - Flask
  core_competencies: 
    - Front-end development
    - API integration
    - Performance optimization
    - Cross-functional teamwork
    - Client interaction
