# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Julio Eduardo Orozco
title: Web Developer
email: jeorozco2002@gmail.com
website: https://github.com/jeorozc0

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: jeorozc0

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name's Julio and I'm a Computer Science Grad at Ball State University. I'm developing my skills on web and application design. I have worked in multiple projects related to finding and solving problems through web development.

# Content Sections
content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Personalized Learning Website
        link: https://github.com/hergin/PersonalizedLearningPlanWebApp
        additional_links:
          - title: Personalized Learning Website
            icon: fab fa-github
            url: https://github.com/hergin/PersonalizedLearningPlanWebApp
        description: |
          This team project aimed to solve the problem of registering the amount of people that get in and out of buses at Ball State. It provided valuable knowledge in .NET programming and teamwork.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Scheidler Apartments
        link: https://www.bsu.edu/map/buildings/campus/scheidler-apartments
        sub_title: Front Desk Assistant
        caption: September 2022 - March 2023
        description: |
          Provided excellent customer service to apartment residents, resolved issues, and organized documents. Cultivated positive community relations through effective communication and conflict resolution.
  - title: Education
    layout: list
    content:
      - layout: left
        title: Ball State University
        caption: 2020 - Present
        sub_title: BSc Computer Science
        quote: |
          Founded in 1918, Ball State University offers highly respected programs in education, architecture, business, communications, fine arts, sciences, humanities, and health professions.
        description: |
          Senior Student pursuing a Bachelor's in Computer Science with a concentration in Web and Application Design.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in web design and software engineering, some of my other hobbies include gaming, reading, and watching movies.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
